### ISSUE TITLE
customize plugin in doker image

### ISSUE THREAD

**Issue by lucafolin** [emqtt/emq_docker#144]
I would like to customize this emqx plugin "emqx_plugin_template", I need to modify this file  "emqx_plugin_template.erl" and then I would like to start my docker container.
How can I do this ? I'm not familiar with docker image.
EMQX_LOADED_PLUGINS dosen't help me because I need to modify my plugin before it starts.

**Comment by Rory-Z** [comment]
Hi, @lucafolin 
Sorry that our mirror does not support this. You can only modify the code and build the mirror yourself. This repo is no longer maintained. You can check how to build the docker image through [emqx/emqx-rel](https://github.com/emqx/emqx-rel/tree/master/deploy/docker)
